### ISSUE TITLE
Cannot build on electron-forge 

### ISSUE THREAD

**Issue by Coder-Iro** [nodegit/nodegit#1873]
## System information
  - node version: 16.5.0
  - npm or yarn version:  3.1.0
  - OS/version/architecture: Windows 11 x64
  - Applicable nodegit version: 0.27.0/0.28.0-alpha.9
  - MSVS Version: 2017

```
node -v
v16.5.0
npm -v # (or yarn -v)
3.1.0
node -e "console.log(process.platform)"
win32
node -e "console.log(require('os').release())"
10.0.22489
node -e "console.log(console.log(process.arch))"
x64
```

## package.json
```json
{
  "name": "gitmc",
  "version": "0.0.1",
  "main": "dist/main.js",
  "description": "Minecraft Modpack Launcher which uses git as updating system",
  "license": "AGPL-3.0-or-later",
  "scripts": {
    "start": "tsc && electron-forge start",
    "package": "tsc && electron-forge package",
    "make": "tsc && electron-forge make"
  },
  "dependencies": {
    "@octokit/rest": "^18.12.0",
    "@xmcl/installer": "^4.0.1",
    "axios": "^0.24.0",
    "electron-squirrel-startup": "^1.0.0",
    "find-java-home": "^1.2.2",
    "nodegit": "0.28.0-alpha.9"
  },
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.61",
    "@electron-forge/maker-deb": "^6.0.0-beta.61",
    "@electron-forge/maker-rpm": "^6.0.0-beta.61",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.61",
    "@electron-forge/maker-zip": "^6.0.0-beta.61",
    "@types/nodegit": "^0",
    "electron": "^15.3.0",
    "typescript": "^4.4.4"
  },
  "packageManager": "yarn@3.1.0",
  "config": {
    "forge": {
      "packagerConfig": {},
      "makers": [
        {
          "name": "@electron-forge/maker-squirrel",
          "config": {
            "name": ""
          }
        },
        {
          "name": "@electron-forge/maker-zip",
          "platforms": [
            "darwin"
          ]
        },
        {
          "name": "@electron-forge/maker-deb",
          "config": {}
        },
        {
          "name": "@electron-forge/maker-rpm",
          "config": {}
        }
      ]
    }
  }
}
```

I'm trying to use nodegit in electron-forge project. When I try to execute `yarn start` or `yarn make`, the error message below is output.
```
c:\users\iro\gitmc\node_modules\nodegit\vendor\libssh2\src\openssl.h(40): fatal error C1083: Cannot open include file.
'openssl/opensslconf.h': No such file or directory [C:\Users\iro\GitMC\node_modules\nodegit\build\vendor\libssh2.vcxproj]
```
There is no error in node-gyp when installing through yarn.

You can see this repository on https://github.com/Coder-Iro/GitMC

**Comment by x90slide** [comment]
I am having the same issue. Did you manage to fix it?

**Comment by ianhattendorf** [comment]
This sounds like https://github.com/nodegit/nodegit/blob/fb0675f6ce8df12091abe1bf77e3aaaf0967408b/generate/templates/templates/binding.gyp#L28 never ran or failed. I'm not sure why this would fail on `electron-forge`.

**Comment by kt-dm** [comment]
@ianhattendorf 

Further up up the logs it is calling that:
```bash
 Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
[1]   Acquiring OpensSL binaries and headers
[1]   HTTPError: Response code 502 (Bad Gateway)
[1]       at EventEmitter.<anonymous> (D:\Experiments\ex1\node_modules\nodegit\node_modules\got\dist\source\as-promise.js:118:31)
[1]       at processTicksAndRejections (internal/process/task_queues.js:95:5)
[1] C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1. [D:\Experiments\ex1\node_modules\nodegit\build\acquireOpenSSL.vcxproj]
[1] C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(209,5): warning MSB8017: A circular dependency has been detected while executing custom build commands for item ".". This may cause incremental build to work incorrectly. [D:\Experiments\ex1\node_modules\nodegit\build\configureLibssh2.vcxproj]
[1]   configure
[1]   [nodegit] Configuring libssh2.
[1]   win_delay_load_hook.cc
[1]   configureLibssh2.vcxproj -> D:\Experiments\ex1\node_modules\nodegit\build\Release\\configureLibssh2.node
[1]   http_parser.c
[1]   win_delay_load_hook.cc
[1]   http_parser.vcxproj -> D:\Experiments\ex1\node_modules\nodegit\build\Release\\http_parser.lib
```

I've tried using the VS2017 MSBuild (Originally using VS2022) tools to see if that makes a difference, but I'm getting the same error when trying to execute `electron-forge start`

I'm not sure if that 502 error call is an issue when trying to `OpensSL binaries and headers`

**Comment by ianhattendorf** [comment]
You'll want to be on at least alpha.11 due to OpenSSL changes, see https://github.com/nodegit/nodegit/blob/master/guides/install/from-source/README.md#electron-and-openssl. We don't currently provide OpenSSL binaries (we used to use Conan but they sunset their old hosting service and don't have a 1:1 replacement) so those will need to be provided by the user when building for Electron currently. OpenSSL can be built automatically if the required dependencies are installed, or a file path/URL specified.

Interesting that the build isn't failing when that section fails, that's a bug that should be fixed.

**Comment by omermecitoglu** [comment]
> You'll want to be on at least alpha.11 due to OpenSSL changes, see https://github.com/nodegit/nodegit/blob/master/guides/install/from-source/README.md#electron-and-openssl. We don't currently provide OpenSSL binaries (we used to use Conan but they sunset their old hosting service and don't have a 1:1 replacement) so those will need to be provided by the user when building for Electron currently. OpenSSL can be built automatically if the required dependencies are installed, or a file path/URL specified.
> 
> Interesting that the build isn't failing when that section fails, that's a bug that should be fixed.

I used this code with `0.28.0-alpha.18` but still can't build, what am i doing wrong?
`npm config set vcvarsall_path "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Auxiliary/Build/vcvarsall.bat"`
